name: "Frogbot Scan Pull Request"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    
    # 1. DEFINE SECRETS AND VARIABLES HERE (JOB LEVEL)
    env:
      JF_URL: ${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
      JF_REQUIRE_ENV: "false" 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Frogbot Scan
        uses: jfrog/frogbot@v2
        # 2. NO "env" BLOCK NEEDED HERE ANYMORE
